---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: Probe-A-Node
  labels:
    app: Probe-A-Node
    component: node
spec:
  selector:
    matchLabels:
      app: Probe-A-Node
      component: node
  template:
    metadata:
      labels:
        app: Probe-A-Node
        component: node
    spec:
      ##hostNetwork: true
      serviceAccountName: Probe-A-Node
      imagePullSecrets:
        - name: harbor-registry-secret      
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      containers:
      - name: Probe-A-Node
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}}}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 9876
          hostPort: 9876
          name: metrics
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9876
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9876
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
        securityContext:
          capabilities:
            add:
              - SYS_NICE
              - NET_BIND_SERVICE
              - CAP_SYS_ADMIN        
        env:
        - name: LOG_LEVEL
          value: "{{ .Values.settings.logLevel }}"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_INTERNAL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_EXTERNAL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: INTERNAL_DNS_ENDPOINT
          value: "{{ .Values.settings.internalDnsEndpoint }}"
        - name: EXTERNAL_DNS_ENDPOINT
          value: "{{ .Values.settings.externalDnsEndpoint }}"
        - name: INTERNAL_DNS_SERVER
          value: "{{ .Values.settings.internalDnsServer }}"
        - name: EXTERNAL_DNS_SERVER
          value: "{{ .Values.settings.externalDnsServer }}"