---
apiVersion: v1
kind: Service
metadata:
  name: Probe-A-Node-node
  labels:
    app: Probe-A-Node
spec:
  type: ClusterIP
  ports:
    - port: 9876
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: Probe-A-Node
    component: node
